# Document Generator - Deployment Configuration
# Dit is het ENIGE bestand dat je moet aanpassen voor deployment

# Google Cloud Project Configuratie
project:
  id: "gen-lang-client-0695866337"  # Vervang met jouw project ID
  region: "europe-west4"
  zone: "europe-west4-a"

# Environment (development, staging, production)
environment: "production"

# Database Configuratie
database:
  name: "document_generator"
  user: "app_user"
  tier: "db-f1-micro"  # Voor production: db-n1-standard-1 of hoger
  disk_size: 20  # GB

# Service Accounts (automatisch aangemaakt door Terraform)
service_accounts:
  app: "document-generator-app"
  deploy: "document-generator-deploy"
  backup: "document-generator-backup"

# Application Configuratie
app:
  name: "document-generator"
  backend_service: "document-generator-backend"
  frontend_service: "document-generator-frontend"
  
  # Resource Limits
  backend:
    memory: "1Gi"
    cpu: "1000m"
    min_instances: 0
    max_instances: 10
  
  frontend:
    memory: "512Mi"
    cpu: "500m"
    min_instances: 0
    max_instances: 5

# Security Configuratie
security:
  jwt_secret_key: ""  # Laat leeg voor automatische generatie
  session_timeout: 60  # minuten
  max_file_size: 10  # MB
  enable_cors: true
  cors_origins: ["*"]

# Email Configuratie (optioneel)
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  smtp_username: ""  # Vul in als je email wilt
  smtp_password: ""  # Vul in als je email wilt
  from_email: ""     # Vul in als je email wilt

# Monitoring & Alerting
monitoring:
  enabled: true
  notification_email: "jan@pvmonteur.nl"  # Vervang met jouw email
  enable_backup: true
  backup_retention_days: 30

# Features
features:
  enable_registration: true
  enable_dark_mode: true
  enable_notifications: true
  enable_debug: false
  enable_rate_limiting: true
  rate_limit_requests: 100  # per minuut per IP

# Storage
storage:
  documents_bucket: ""  # Automatisch gegenereerd
  templates_bucket: ""  # Automatisch gegenereerd
  backups_bucket: ""    # Automatisch gegenereerd

# Google APIs (optioneel - voor Google Docs/Sheets integratie)
google_apis:
  oauth_client_id: ""     # Vul in voor Google integratie
  oauth_client_secret: "" # Vul in voor Google integratie

# Advanced Settings (normaal niet aanpassen)
advanced:
  log_level: "INFO"
  request_timeout: 300
  database_pool_size: 5
  enable_ssl: true
  
# GitHub Repository (voor CI/CD)
github:
  repository: "Jan1986-cloud/document-generator"
  branch: "main"
